# Generated by Django 4.2.6 on 2023-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('Edad', models.PositiveBigIntegerField()),
                ('numero_telefonico', models.PositiveBigIntegerField()),
                ('correo_electronico', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Registro_cliente',
            },
        ),
    ]
